$FirebaseSDKVersion = '11.15.0'
# Resolve react_native_pods.rb with node to allow for hoisting
 def node_require(script)
    # Giải quyết tập lệnh với node để cho phép hoisting
    require Pod::Executable.execute_command('node', ['-p',
      "require.resolve( 
        '#{script}',
        {paths: [process.argv[1]]},
      )", __dir__]).strip 
 end

# Sử dụng lệnh này để yêu cầu cả các tập lệnh của react-native và của gói này:
 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ⬇️ Bỏ chú thích các quyền bạn cần
setup_permissions ( [
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
   'Camera',
  # 'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
   'MediaLibrary',
  # 'Microphone',
  # 'Motion',
   'Notifications',
  # 'PhotoLibrary',
   'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
] )


linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'NewMWay' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
