export enum BankName {
    VietinBank = "VietinBank",
    Vietcombank = "Vietcombank",
    MBBank = "MBBank",
    ACB = "ACB",
    VPBank = "VPBank",
    TPBank = "TPBank",
    MSB = "MSB",
    NamABank = "NamABank",
    LienVietPostBank = "LienVietPostBank",
    VietCapitalBank = "VietCapitalBank",
    BIDV = "BIDV",
    Sacombank = "Sacombank",
    VIB = "VIB",
    HDBank = "HDBank",
    SeABank = "SeABank",
    GPBank = "GPBank",
    PVcomBank = "PVcomBank",
    PVcomBankPay = "PVcomBankPay",
    NCB = "NCB",
    ShinhanBank = "ShinhanBank",
    SCB = "SCB",
    PGBank = "PGBank",
    Agribank = "Agribank",
    Techcombank = "Techcombank",
    SaigonBank = "SaigonBank",
    DongABank = "DongABank",
    BacABank = "BacABank",
    StandardChartered = "StandardChartered",
    Oceanbank = "Oceanbank",
    VRB = "VRB",
    ABBANK = "ABBANK",
    VietABank = "VietABank",
    Eximbank = "Eximbank",
    VietBank = "VietBank",
    IndovinaBank = "IndovinaBank",
    BaoVietBank = "BaoVietBank",
    PublicBank = "PublicBank",
    SHB = "SHB",
    CBBank = "CBBank",
    OCB = "OCB",
    KienLongBank = "KienLongBank",
    CIMB = "CIMB",
    HSBC = "HSBC",
    DBSBank = "DBSBank",
    Nonghyup = "Nonghyup",
    HongLeong = "HongLeong",
    IBKBank = "IBK Bank",
    Woori = "Woori",
    UnitedOverseas = "UnitedOverseas",
    KookminHN = "KookminHN",
    KookminHCM = "KookminHCM",
    COOPBANK = "COOPBANK"
}

// export const BANK_NAMES = [
//   "VietinBank",
//   "Vietcombank",
//   "MBBank",
//   "ACB",
//   "VPBank",
//   "TPBank",
//   "MSB",
//   "NamABank",
//   "LienVietPostBank",
//   "VietCapitalBank",
//   "BIDV",
//   "Sacombank",
//   "VIB",
//   "HDBank",
//   "SeABank",
//   "GPBank",
//   "PVcomBank",
//   "PVcomBankPay",
//   "NCB",
//   "ShinhanBank",
//   "SCB",
//   "PGBank",
//   "Agribank",
//   "Techcombank",
//   "SaigonBank",
//   "DongABank",
//   "BacABank",
//   "StandardChartered",
//   "Oceanbank",
//   "VRB",
//   "ABBANK",
//   "VietABank",
//   "Eximbank",
//   "VietBank",
//   "IndovinaBank",
//   "BaoVietBank",
//   "PublicBank",
//   "SHB",
//   "CBBank",
//   "OCB",
//   "KienLongBank",
//   "CIMB",
//   "HSBC",
//   "DBSBank",
//   "Nonghyup",
//   "HongLeong",
//   "IBK Bank",
//   "IBK Bank",
//   "Woori",
//   "UnitedOverseas",
//   "KookminHN",
//   "KookminHCM",
//   "COOPBANK"
// ] as const;